language: ruby
bundler_args: --without development
sudo: false
rvm: 2.4.2
services: mongodb
script: bundle exec rspec spec
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "TDNa5mXBQ+M6qYlhimT+yBEuMS8ox0ceCtISUBYrhsdYZD/GPgWSds1AvmnUjGyf9sW8OwmtfppdEnOnro8fitpV8eRHVCJ05y49DDbJK9KtvISJZKOq2VOiHTkTAY8njUstjQ2xGv35gdvxpfg26/0a7TapZ6aYhuAX1q0Ov44="
  app: steam-card-tracker
  on:
    repo: pboksz/steam-card-tracker
notifications:
  email: false
