language: ruby
bundler_args: --without development
sudo: false
rvm: 2.4.2
services: mongodb
script: xvfb-run bundle exec rspec spec
addons:
  code_climate:
    repo_token:
      secure: I7G4oQ/oxjgAQMMHYiHWMRW3V2azRD/NEYnNyJ/BbUUYFY1o76BEenkVqZ1N4PnTPXVeD8ThMEY3II/gTIT/uAb5SLejj1U8E0RTnO9zoOsXRR62XlSdsZvQqDzje3Dr1JxWz24WQ+qLYIyP5dY6UPbx/Z0snx9sAO2TXH6EJEU=
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "TDNa5mXBQ+M6qYlhimT+yBEuMS8ox0ceCtISUBYrhsdYZD/GPgWSds1AvmnUjGyf9sW8OwmtfppdEnOnro8fitpV8eRHVCJ05y49DDbJK9KtvISJZKOq2VOiHTkTAY8njUstjQ2xGv35gdvxpfg26/0a7TapZ6aYhuAX1q0Ov44="
  app: steam-card-tracker
  on:
    repo: pboksz/steam-card-tracker
notifications:
  email: false
