version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mongo:4.2
        port: 27017
        environment:
          - MONGODB_USERNAME: "root"
          - MONGODB_PASSWORD: "pass"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: Install MongoDB
          command: sudo apt-get install -y mongodb

      - run:
          name: Wait For Database
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - run:
          name: Add Database Admin
          command: |
            mongodb && mongo --eval 'db.createUser({ user: "root", pwd: "pass", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] })'

      - run:
          name: Run Specs
          command: bundle exec rspec --format progress --profile 10 spec

  deploy:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
