development:
  sessions:
    default:
      database: steam_card_tracker_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: steam_card_tracker_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        max_retries: 10
        retry_interval: 30
