development:
  clients:
    default:
      database: steam_card_tracker_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: steam_card_tracker_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
